# Generated by Django 4.1 on 2022-09-23 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPedidos_APP', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('categoria', models.CharField(max_length=20)),
                ('precio', models.IntegerField()),
            ],
        ),
    ]
